#!/usr/bin/with-contenv /bin/sh

hash_certs() {
    find /.lego/certificates \
        -type f \
        -exec python -sBc "import hashlib;print hashlib.md5(open('{}','rb').read()).hexdigest()" \;
}
PRE_HASH=$(hash_certs)

lego \
    --path="/.lego" \
    --server="${LEGO_SERVER:=https://acme-v01.api.letsencrypt.org/directory}" \
    --email="${EMAIL}" \
    --domains=${DOMAINS} \
    --dns="route53" \
    --days="${RENEW_DAYS:="30"}" \
    renew 

if [ "${PRE_HASH}" = "$(hash_certs)" ]; then
    echo "Certificate is still valid for at least ${RENEW_DAYS} days."
    exit 0
fi

# Certificate(s) have changed, so push to S3...
aws s3 sync /.lego "${S3LEGO}"

# ... and make nginx reload.
killall -HUP nginx
