#!/usr/bin/with-contenv /bin/sh

mkdir -p /.lego

# pull down the lego directory from S3
aws s3 sync "${S3LEGO}" /.lego

# issue the certificate
#lego \
    #--path="/.lego" \
    #--server="${LEGO_SERVER:=https://acme-v01.api.letsencrypt.org/directory}" \
    #--email="${EMAIL}" \
    #--domains="${DOMAINS}" \
    #--dns="route53" \
    #run 

# send the lego directory up to S3
# aws s3 sync /.lego "${S3LEGO}" 
